apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - env:
        - name: ADMIN_PASS
          value: 89*qcF$$P[
        - name: ADMIN_USER
          value: admin
        - name: APPLICATION_USER
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: username
        - name: APPLICATION_PASS
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: password
        - name: APPLICATION_DATABASE
          value: testra
        - name: AUTH
          value: "yes"
        image: vepo/mongo
        name: testra-mongo
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
