apiVersion: v1
kind: Service
metadata:
  name: testra-api
spec:
  type: LoadBalancer
  selector:
    app: testra-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    app: testra-api
  name: testra-api
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: testra-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        app: testra-api
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
        image: testra/testra-api:1.0-m1
        name: testra-api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
