apiVersion: v1
kind: Service
metadata:
  name: testra-api
spec:
  type: LoadBalancer
  selector:
    app: testra-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    app: testra-api
  name: testra-api
spec:
  replicas: 2
  strategy: {}
  selector:
    matchLabels:
      app: testra-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        app: testra-api
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: testra
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: username
#          value: testra
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: password
#          value: 89*qcC$$P[
        image: pauljohnson2sky/testra-api:1.0
        name: testra-api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
